services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-review-app
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=book_store
      - DB_USERNAME=root
      - DB_PASSWORD=root
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - mysql
    networks:
      - book-review-network

  mysql:
    image: mariadb:10.8.3
    container_name: book-review-mysql
    # Uncomment below when on Mac M1
    # platform: linux/arm64/v8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: book_store
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - book-review-network

  adminer:
    image: adminer
    container_name: book-review-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - book-review-network

networks:
  book-review-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
